### PR TITLE
add slack.channels.replies to channels module

### PR DESCRIPTION
**Pull request by kenyo**
noticed this after trying to call `slack.channels.replies`

### CODE REVIEW

**Comment by brianleroux** [comment]
on a bad mobile so I'm unable to publish to npm but will aim to get it out there today!

**Comment by kenyo** [comment]
thanks brian! big fan of this lib 👍

**Comment by brianleroux** [comment]
omg I finally got to a place w WiFi and for some reason it doesn't seems to support WebSocket (lol-tastic) --- are you interested in being a collaborator here and npm? (this way you can publish a patch w/o relying on my sketchy connectivity!!)

**Comment by brianleroux** [comment]
SUPER SORRY this took so darn long. Learned some tough lessons about web sockets in south america! Latest is published to npm. 💟

**Pull request merged**
