### PR TITLE
update channel imports

### PR DESCRIPTION
**Pull request by matthewmueller**

### CODE REVIEW

**Comment by dariocravero** [comment]
@brianleroux could you merge this in and publish a new version? thanks! :)

**Comment by brianleroux** [comment]
woah! thx (sorry missed the notification the first time!)

**Comment by brianleroux** [comment]
(gimme 5 and a new ver will be up on npm)

**Comment by brianleroux** [comment]
just published a new minor for this / sorry for the delay!

**Comment by dariocravero** [comment]
cool :) thanks!

**Pull request merged**
