### PR TITLE
Version 9.0.0

### PR DESCRIPTION
**Pull request by brianleroux**
Big release! 

Stuff that says the same:

- old school Web API methods in node errback style
- tested for all Node LTS versions
- tested in a recent Chrome

New Shiny:

- `slack` is now not just a namespace but also a class constructor / factory function `const bot = new Slack({token})` returns an object with all methods bound with `token`
- all methods now return a `Promise` if an errback is not supplied 🙀 
- browser build is now **7KB** <small>small</small> 😱😱😱 

Breaking changes:

- removes `slack.api.client`
- removes `slack.rtm.client` and thusly support for Slack RTM API

Dev changes:

- removes Babel 

Feedback super appreciated! 💯  cc @afabbro @spencermountain @mbrevoort

### CODE REVIEW

**Comment by spencermountain** [comment]
> all methods now return a Promise if an errback is not supplied

i think that is really clever. it's kindof the perfect async api.

**Comment by mbrevoort** [comment]
@brianleroux this looks tight! All for removing RTM, not a big promise fan but love the seemless fallforward to it. I’ll test it later today to see if there are any surprises.

**Comment by brianleroux** [comment]
Draft blawg post to announce (cc @ryanblock!) https://medium.com/@brianleroux/introducing-slack-js-9-0-0-c425a63cc479

**Comment by mbrevoort** [comment]
👍 Blog post LGTM

**Comment by brianleroux** [comment]
Everyone lmk if you have any last min changes otherwise I aim to publish after lunch!!

**Pull request merged**
