### PR TITLE
Generate new types

### PR DESCRIPTION
**Pull request by danprince**
Looks like we never added the generate-types script to the generate task. Just added it and generated the most recent round of API changes. Should be ready for a new patch release.

### CODE REVIEW

**Comment by brianleroux** [comment]
removing package-lock.json did the trick (it should probably be a thing for apps not libs anyhow I think?)

**Comment by danprince** [comment]
I think technically it's supposed to work for both, but I've seen a handful of projects gitignore it.

Can I get an invite to the codeship org? Can't actually see the error for the failed build.

**Comment by brianleroux** [comment]
yea for sure: invite sent! 

(also: feel free to merge/publish a fresh version)

**Comment by danprince** [comment]
Published as 9.1.3!

**Pull request merged**
