### PR TITLE
Update with latest Slack API methods

### PR DESCRIPTION
**Pull request by mbrevoort**
Updated for latest Slack API

neverupdate

Added methods:
- `auth.revoke`
- `bots.info`
- `chat.meMessage`
- `team.billableInfo`
- `files.comments`
- `reminders`

Updated README with latest events and methods

Added `SLACK_BOT_TOKEN` for tests specifically for a bot user since a bot user does not have the channels:history scope. The `SLACK_TOKEN` is used to test for channel history.

### CODE REVIEW

**Comment by brianleroux** [comment]
<3 thx mang! just publishing to npm as `7.4.0`

**Comment by brianleroux** [comment]
eh @mbrevoort lmk if you want github/npm collab access to publish builds 👊 ✨

**Comment by mbrevoort** [comment]
@brianleroux yeah, if it's cool, go ahead and add me as a collaborator 👪

**Comment by brianleroux** [comment]
Github collab thingo sent! 📬 (And ur added to https://www.npmjs.com/package/slack)

double-doge

**Pull request merged**
